# Generated by Django 4.2.5 on 2023-09-08 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(default='', max_length=190)),
                ('createAT', models.DateField(default=datetime.datetime.now)),
                ('update', models.DateField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=False)),
                ('descript', models.TextField(default='write here')),
            ],
        ),
    ]
