# Generated by Django 4.2.5 on 2023-09-08 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descript',
            new_name='description',
        ),
    ]
